baseURL = "https://milano_pollution.github.io/"
languageCode = "en-us"
title = "Hugo Whisper Theme"
theme = "D:/All/socialdata2021/website/quickstart/themes/hugo-whipser-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "CO"
    url = "/co/"
    weight = 2

[[menu.main]]
    name = "NO2"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Statistics"
    url = "/statistics/"
    weight = 2
    
[[menu.main]]
    name = "Story"
    url = "/story/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true



  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
